### ISSUE TITLE
BACKEND_URL &  POCKETBASE_URL

### ISSUE THREAD

**Issue by tamaskan** [goniszewski/grimoire#70]
in: src/lib/config.ts

shouldn't those two get their values from two different environment-variables to define the front & backend ?

best regards

**Comment by goniszewski** [comment]
Hello @tamaskan! These two values are poorly named, I admit it. If the PB is being deployed by Docker Compose method, the `BACKEND_URL` will be different from `POCKETBASE_URL`, but if the app is run in dev mode (or the PB instance is an external one), the URL will be the same.

I want to simplify the configuration and the deployment process in the near future.

**Comment by SrGeneroso** [comment]
I'm not sure if the docs are outdated or if is related to this conversation, but the docker example, when you don't change the .env.example defaults, it doesn't work.
I think is related to this setting.
```bash
# Set it if you're using external PocketBase installation (default: http://localhost:8090)
# Example: PUBLIC_POCKETBASE_URL=https://grimoire.mydomain.com:8090
PUBLIC_POCKETBASE_URL=
```
which doesn't default to localhost but to pocketbase:80
![image](https://github.com/goniszewski/grimoire/assets/5541794/302b133b-3b54-4b5e-a82c-279dedbe980e)

Is that correct? the issue comes that the dashboard can't connect to pocketbase
![image](https://github.com/goniszewski/grimoire/assets/5541794/340c39eb-8dac-42d3-bea8-a5ea31e792a4) because is trying to reach a "domain" instead of localhost 
![image](https://github.com/goniszewski/grimoire/assets/5541794/b48fdd1c-e13d-4693-84cc-242bdafe9ad9)

**Comment by goniszewski** [comment]
@SrGeneroso It's failing for me too - calling it (PocketBase) directly from the app container on `http://pocketbase/api/health` also doesn't work. I will look into this today.

@tamaskan PB does use `Authorization: TOKEN` header approach to handle authentication.

**Comment by goniszewski** [comment]
I have removed `BACKEND_URL` completely, so now there's only `POCKETBASE_URL` config option (`PUBLIC_POCKETBASE_URL` in `.env`) that defaults to `http://localhost:8090`.

Currently, only the URLs to files stored in PB are proxied through the app instance, but my goal is to proxy all PB calls through Grimoire itself - it will further simplify networking in the deployed project.
